location = "/home/bryley/nixos-flake"
publicKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILPANRYprsXkHoTidipqDKIQfhnTkGiPpLwiEKlfSq5Y bryley@Bryleys-MacBook-Pro.local",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBHmralFbmz2VmU2Cv9beabaDWoTdTRITqrvipXqdGdC bryley@laptop",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ04D3ggEOIUsitrtqq3EsYh5899TvrugzPN64Jrxy3j bryley@laptop",
]

[[users]]
name = "bryley"
fullName = "Bryley Hayter"
email = "bryleyhayter@gmail.com"
admin = true

[[hosts]]
name = "laptop"
disk = "nvme0n1"
system = "x86_64-linux"
headless = false

[[hosts]]
name = "work-vm"
disk = "vda"
system = "aarch64-linux"
headless = true

[[hosts]]
name = "laptop-vm"
disk = "vda"
system = "x86_64-linux"
headless = false

[[hosts]]
name = "test-vm"
disk = "vda"
system = "x86_64-linux"
headless = false
